[package]
name = "rustface"
version = "0.1.0"
authors = ["Andrei Tomashpolskiy <nordmann89@gmail.com>"]

[dependencies]
num = "0.1.41"
byteorder = "1.2.1"
stdsimd = "0.0.3"
opencv = { version = "0.2.3", optional = true }

[features]
opencv-demo = ["opencv"]

[[bin]]
required-features = ["opencv-demo"]
name = "opencv_demo"