[package]
name = "rustface"
description = "Face detection library, based on the C++ SeetaFace engine."
version = "0.1.0"
repository = "https://github.com/atomashpolskiy/rustface"
readme = "README.md"
keywords = ["face", "detection"]
categories = ["multimedia::images", "science"]
authors = ["Andrei Tomashpolskiy <nordmann89@gmail.com>"]
license = "BSD-2-Clause"
exclude = [
    "assets/*",
]

[dependencies]
num = "0.1.41"
byteorder = "1.2.1"
stdsimd = "0.0.3"
rayon = "0.9.0"

[dev-dependencies]
opencv = "0.2.3"
cpuprofiler = "0.0.3"

[profile.release]
lto = true